export const studentTemplate = {
  firstName: "",
  lastName: "",
  dateOfBirth: "",
  sex: "male",
  age: "",
  grade: "Pre-K",
  group: "",
  returningDancer: false,
  mailingAddress: "",
  address: "",
  city: "",
  state: "NY",
  zip: "",
  mobile: "",
  email: "",
  additionalInformation: "",
  receiveIncomingTextMessages: "",
  paidTuition: "",
};
