export const studentTemplate = {
  firstName: "",
  lastName: "",
  dateOfBirth: "",
  age: "",
  grade: "",
  group: "",
  returningDancer: false,
  mailingAddress: "",
  address: "",
  city: "",
  state: "",
  zip: "",
  mobile: "",
  email: "",
  additionalInformation: "",
  receiveIncomingTextMessages: "",
  paidTuition: "",
};
